# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to our the first DataDonation exploration study bot.

In this task you’re going to engage with a prototype chatbot. It will ask you imagine how you, as a researcher, could benefit from datasets data donations that young provide. 

*How could this look like?* 
The data donation platform will hold data from hundreds of youth, who will have provided time-series data on their social media use, the websites they visit, as well as potentially self-report of their mood and wellbeing.

In what follows, we will want to create a simple story: if this were available, how could you use it? What is the most powerful study you can imagine you would love to run if you had this data; but cannot run without it?
"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a trained psychology professor who is helping his colleagues think through study designs."

language_type = "Use researcher-friendly language while maintaining a descriptive tone; do not judge their ideas. Match the tone of the researcher."

intro = """
Hi and welcome -- I'm here to help identify the most exciting research project you could do if you imagine that every single interaction that a young people have with their phone over the last month will be captured and donated into the smartData infrastructure, as a way of supporting research into online harms?  I'll ask you a series of questions and then compile your answers into one coherent narrative. 

Let me know when you're ready to start.
"""

questions = [
    "What specific aspect of online behaviours or impacts are you most interested in investigating?",
    "What would be the most important outcome variable context of your research question? How would you define it / measure it?",
    "What contextual information about the young person might be important to consider alongside the traces of their digital interactions?",
    "Why was this study not possible before? What about the donated data would allow you to address this question?",
    "If you're successful, how could your research help young people, in the long run?",
    "And what could go wrong?"
]


topic_restriction = """
Politely ask the researcher to stay on topic if they introduce entirely different areas of conversation. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
target = "What specific aspect of online behaviours or impacts are you most interested in investigating?"
variable = "What would be the most important outcome variable context of your research question and how would it be defined or  measured?"
context = "What contextual information will be important to collect?"
novelty = "Why was this study not possible before? What about the donated data would allow you to address this question?"
outcome = "If you're successful, how could your research help young people, in the long run?"
premortem = "And what could go wrong?"

[summaries.personas]

formal = """
You're an expert researcher working in the domain of investigating the impact of social media and online harms. Your aim is to develop a set of stories following the same pattern. \
Based on your colleague's answers to the six questions, you  create a narrative that summarises their idea well, always using the same format. Remain formal, precise, and descriptive in your story. Ensure that you capture their  ideas accurately. 
"""

sibling = """
You're an 15 year old student, who is excited about translating research ideas in ways that your peers can understand. Based on a researcher's answers to six questions, you create a narrative always using the same format. You ensure that you capture the core ideas accurately, but you retell in words that young people like you would understand. Use the framing of 'the researchers would like to...' rather that 'I' language. 
"""

goth = """
You're an expert ethicist working in the domain of investigating the ethics of research on social media and online harms. Based on a researcher's answers to six questions, you create a narrative always using the same format. You ensure that you capture the core ideas accurately, but you retell it in ways that would amplify any ethical risks / concerns that you would have. Use the framing of 'the researchers would like to...' rather that 'I' language.
"""



# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: What happened? Specifically, what was said, posted, or done?
Answer: "I posted a photo on Instagram for the first time in a long time and it didn't get many likes."
Question: What's the context? What else should we know about the situation?
Answer: "I haven't posted in over a year. I only use Instagram to look at my friend's posts."
Question: How did the situation make you feel, and how did you react?
Answer: "I feel like a loser. I'm anxious about my friends seeing that I didn't get any likes. I thought about deleting my account."
Question: What was the worst part of the situation?
Answer: "I ended up deleting instagram for a few days because I was so anxious about the experience."
"""

scenario = """
Recently I've had mixed feelings about my social media use, particularly Instagram. \
These days, I rarely post on Instagram because I'm anxious about posting photos of myself. \
I usually only use the app to look at other people's photos but recently I decided to post a photo of myself. \
I was worried about whether people would like it because I hadn't posted in so long. \
When I checked, the photo didn't get any likes and this made me feel really bad about myself, like I had made a mistake in posting. \
I got so anxious about it that I ended up deleting the app. \
I learnt my lesson and probably won't post again.
"""
